/** Try statements can be implicitly nested via calls to method. */

public class MethNestTry {

    public static void nesttry(int a) {
        try { // nested try

            /*
             * If one command-line arg is used,
             * then a divide-by-zero exception
             * will be generated by follwing code.
             */

            if (a == 1)
                a = a / (a - a); // division by zero.

            /*
             * If two command-line args are used,
             * then generated an out-of-bound exception.
             */

            if (a == 2) {
                int c[] = { 1 };
                c[26] = 99; // generate an out-of-bound exception
            }

        } 
        catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Array index out-of-bounds: " + e);
        }
    }

    public static void main(String[] args) {
        try {
            int a = args.length;

            /*
             * If no command-line args are present,
             * the following statement will generate
             * a divide-by-zero exception.
             */

            int b = 42 / a;
            System.out.println("a = " + a + " b = " + b);

            nesttry(a);
        } 
        catch (ArithmeticException e) {
            System.out.println("Divide by 0: " + e);
        }
    }
}
